language: java
jdk: oraclejdk7
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $PWD/gradle-2.14.1/

before_install:
  # Gradle
  - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  - unzip -n gradle-2.14.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  
script: gradle -b cn.ieclipse.aorm.core/build.gradle test assemble

